#! /bin/sh
FILE="/sys/power/state"
STATE="mem"
if [ $# -eq 1 ]
  then
   if [[ $1 == "hibernate" ]]; then
      STATE="disk"
   elif [[ $1 == "freeze" ]]; then
      STATE="freeze"
fi
fi
if test -f "$FILE"; then
   $(echo $STATE >$FILE)
fi

