#! /bin/sh
FILE="/sys/power/state"
STATE="mem"
if [ $# -eq 1 ]
  then
   if [ "$1" = "hibernate" ]; then
      STATE="disk"
   elif [ "$1" = "freeze" ]; then
      STATE="freeze"
   else
      echo run fpm as root to suspend
      echo run fpm hibernate as root to hibernate
      echo run fpm freeze as root to freeze
      return 126
fi
fi
if test -f "$FILE"; then
   if grep -q $STATE "$FILE"; then
      echo $STATE > $FILE
   else
      echo action not supported
      return 1
   fi
fi

